[package]
name = "sea2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stdweb = "0.4.20"
yew = "0.20.0"

[[bin]]
name = "sea2023"
path = "main.rs"
